#!/bin/bash
# Usage pull_request <branch>

ref=$(git symbolic-ref HEAD 2> /dev/null) || return
branch=${ref#refs/heads/}
origin=$(git config --get remote.origin.url | sed "s/^.*:\(.*\)\/.*$/\1/g")
default_branch=`git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'`

if [[ -z $default_branch ]]; then
  default_branch="master"
fi

if [[ -z $1 ]]; then
  target="$default_branch"
else
  target="$1"
fi

args="-o"

template="$PWD/.github/PULL_REQUEST_TEMPLATE.md"

git push origin $branch

if [[ -e $template ]]; then
  url=`hub compare -u $branch`
  open "$url?expand=1"
else
  hub pull-request $args -h $origin:$branch -b $target
fi

