#!/usr/bin/python

import fnmatch
import os
import re
import sys
import shutil
import getopt

class Rename1:
    def Rename(self, file):
        return basename + " - " +  m.group().upper() + ".avi"

class Rename2:
    def Rename(self, file):
        [season, episode] = m.group().rsplit('-');
        token = "S%02dE%02d" % (int(season), int(episode))
        return basename + " - " + token + ".avi"

class Rename3:
    def Rename(self, file):
        return basename + " - " +  m.group().upper().replace('X','E') + ".avi"

class Rename4:
    def Rename(self, file):
        season = m.group()[0];
        episode = m.group()[1:3];
        token = "S%02dE%02d" % (int(season), int(episode))
        return basename + " - " + token + ".avi"

filesToRename = []

basename = sys.argv[1]

regexes = {"[s|S]\d+[e|E]\d+": Rename1(),
           "\d+-\d+": Rename2(),
           "[s|S]\d+[x|x]\d+": Rename3(),
           "\d\d\d": Rename4()}

for file in os.listdir('.'):
    if fnmatch.fnmatch(file, '*.avi'):
        filesToRename.append(file) 

for file in filesToRename:
    found = False
    for regexString, renamer in regexes.items():    
        regex = re.compile(regexString);
        m = regex.search(file)
        if m != None:
            src = file 
            dst = renamer.Rename(file)
            shutil.move(src, dst)
            #print "cp " + src + " " +  dst
            found = True
    if found == False:
        print 'Nothing found: ' + file

