#!/bin/bash
default_branch=`git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'`

if [[ -z $default_branch ]]; then
  default_branch="master"
fi

if [[ -z $1 ]]; then
  target="$default_branch"
else
  target="$1"
fi

git diff --name-only $target | \
  xargs ls -d 2>/dev/null | \
  xargs bundle exec rubocop -a --force-exclusion
