#!/bin/bash

set -e

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

PYTHON_VERSION=`pyenv latest 3`
pyenv shell $PYTHON_VERSION
pip install --upgrade aider-chat
aider $@
